/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.4.2/userguide/building_java_projects.html
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    base
    java
    `java-gradle-plugin`
    `maven-publish`
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
    gradlePluginPortal()
}

dependencies {
    implementation(gradleApi())
    implementation("com.fasterxml.jackson.core:jackson-databind:2.20.0")
    testImplementation("org.assertj:assertj-core:3.27.4")
}

gradlePlugin {
    plugins {
        register("xRegistryOCIPackaging") {
            id = "com.metaformsystems.xregistry-oci-packaging"
            implementationClass = "com.metaformsystems.fleet.XRegistryOciPackagingPlugin"
        }
    }
}

testing {
    suites {
        // Configure the built-in test suite
        val test by getting(JvmTestSuite::class) {
            // Use JUnit Jupiter test framework
            useJUnitJupiter("5.8.1")
        }
    }
}

// Clean up build artifacts
tasks.clean {
    delete(
        layout.buildDirectory.dir("xregistry-staging"),
        layout.buildDirectory.dir("oci-layers"),
        layout.buildDirectory.dir("oci-config"),
        layout.buildDirectory.dir("oci-manifest"),
        layout.buildDirectory.dir("oci-layout"),
        layout.buildDirectory.dir("distributions")
    )
}

project.defaultTasks("buildXRegistryOci")

publishing {
    publications {
        create<MavenPublication>("maven") {
            from(components["java"])
        }
    }
}