/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.4.2/userguide/building_java_projects.html
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    base
    `java-gradle-plugin`
}

repositories {
    gradlePluginPortal()
}

dependencies {
    implementation(gradleApi())
}

gradlePlugin {
    plugins {
        register("xRegistryOCIPackaging") {
            id = "com.metaformsystems.xregistry-oci-packaging"
            implementationClass = "com.metaformsystems.fleet.XRegistryOciPackagingPlugin"
        }
    }
}

// Clean up build artifacts
tasks.clean {
    delete(
        layout.buildDirectory.dir("xregistry-staging"),
        layout.buildDirectory.dir("oci-layers"),
        layout.buildDirectory.dir("oci-config"),
        layout.buildDirectory.dir("oci-manifest"),
        layout.buildDirectory.dir("oci-layout"),
        layout.buildDirectory.dir("distributions")
    )
}

project.defaultTasks("buildXRegistryOci")

publishing {
    publications {
        create<MavenPublication>("maven") {
            from(components["java"])
        }
    }
}